fn main() {
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("macos") {
        cc::Build::new().file("native/record_media.m").flag("-fobjc-arc").flag("-fblocks").flag("-Wno-deprecated-declarations").compile("qingbox_record_media");
        println!("cargo:rerun-if-changed=native/record_media.m");
        for framework in ["AVFoundation", "CoreMedia", "Foundation"] { println!("cargo:rustc-link-lib=framework={framework}"); }
    }
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "list_shortcuts", "save_shortcut_binding", "set_shortcut_recording", "start_recording_command", "record_start", "record_cancel", "record_status", "record_stop", "record_card_action", "start_screenshot_command", "capture_cancel", "capture_ready", "capture_long_start", "capture_long_finish", "capture_long_export", "capture_long_cancel", "capture_export", "pin_close", "pin_scale", "pin_copy", "toggle_fullscreen", "hide_launcher", "resize_launcher",
            "open_settings", "close_settings", "complete_directory", "begin_search_session",
            "search_files", "get_application_icon", "open_path", "list_plugin_commands",
            "open_plugin", "leave_plugin", "plugin_call", "list_plugins", "reload_plugins", "set_plugin_enabled", "import_plugin", "remove_plugin",
        ]),
    )).expect("构建应用权限失败");
    // 新录屏权限文件的说明保持简体中文；Tauri 每次构建都会重新生成英文模板。
    for command in ["start_recording_command", "record_start", "record_cancel", "record_status", "record_stop", "record_card_action"] {
        let path = format!("permissions/autogenerated/{command}.toml");
        let content = std::fs::read_to_string(&path).expect("读取录屏权限文件失败")
            .replace("# Automatically generated - DO NOT EDIT!", "# 由构建脚本自动生成，请勿手动修改。")
            .replace(&format!("Enables the {command} command without any pre-configured scope."), &format!("允许调用 {command} 命令，窗口与会话范围由宿主校验。"))
            .replace(&format!("Denies the {command} command without any pre-configured scope."), &format!("禁止调用 {command} 命令。"));
        std::fs::write(path, content).expect("保存中文录屏权限文件失败");
    }
}
