use super::{Capture, Kind, MAX_ITEM_BYTES};
use crate::plugins::CallError;
use objc2::{rc::autoreleasepool, runtime::ProtocolObject, AllocAnyThread};
use objc2_app_kit::{NSBitmapImageFileType, NSBitmapImageRep, NSCompositingOperation, NSDeviceRGBColorSpace, NSGraphicsContext, NSImage, NSPasteboard, NSPasteboardItem, NSPasteboardTypeFileURL, NSPasteboardTypePNG, NSPasteboardTypeString, NSPasteboardTypeTIFF, NSPasteboardWriting};
use objc2_foundation::{NSArray, NSData, NSDictionary, NSPoint, NSRect, NSSize, NSString};
use std::sync::atomic::{AtomicIsize, Ordering};

pub fn capture_changed(last_change: &AtomicIsize) -> Result<Option<Capture>, String> {
    autoreleasepool(|_| {
        let pasteboard = NSPasteboard::generalPasteboard();
        let change = pasteboard.changeCount();
        if change == last_change.load(Ordering::SeqCst) { return Ok(None) }
        let result = read(&pasteboard);
        // 复制期间内容可能由应用延迟提供，空剪贴板与变化中的快照稍后重读。
        if pasteboard.changeCount() != change { return Ok(None) }
        if pasteboard.types().is_some_and(|types| !types.is_empty()) { last_change.store(change, Ordering::SeqCst); }
        result
    })
}

fn read(pasteboard: &NSPasteboard) -> Result<Option<Capture>, String> {
    if pasteboard.types().is_some_and(|types| types.iter().any(|value| matches!(value.to_string().as_str(),
        "org.nspasteboard.ConcealedType" | "org.nspasteboard.TransientType" | "org.nspasteboard.AutoGeneratedType"))) { return Ok(None) }
    let mut files = vec![];
    if let Some(items) = pasteboard.pasteboardItems() {
        for item in items.iter() {
            if let Some(url) = item.stringForType(unsafe { NSPasteboardTypeFileURL }) {
                let url = tauri::Url::parse(&url.to_string()).map_err(|_| "剪贴板文件地址不正确")?;
                let path = url.to_file_path().map_err(|_| "剪贴板中不是本机文件地址")?;
                files.push(path.to_string_lossy().into_owned());
            }
        }
    }
    if !files.is_empty() { return Capture::files(files).map(Some) }
    for kind in [unsafe { NSPasteboardTypePNG }, unsafe { NSPasteboardTypeTIFF }, &NSString::from_str("public.jpeg")] {
        if let Some(data) = pasteboard.dataForType(kind) {
            if data.length() > MAX_ITEM_BYTES { return Err("图片超过 20 MB，未加入历史".into()) }
            return image(&data).map(Some);
        }
    }
    if let Some(text) = pasteboard.stringForType(unsafe { NSPasteboardTypeString }) {
        if !text.is_empty() { return Capture::text(text.to_string()).map(Some) }
    }
    Ok(None)
}

fn image(data: &NSData) -> Result<Capture, String> {
    let bitmap = NSBitmapImageRep::initWithData(NSBitmapImageRep::alloc(), data).ok_or("无法读取剪贴板图片")?;
    let (width, height) = (bitmap.pixelsWide(), bitmap.pixelsHigh());
    if width <= 0 || height <= 0 || width.saturating_mul(height) > 40_000_000 { return Err("图片尺寸过大，未加入历史".into()) }
    let png = unsafe { bitmap.representationUsingType_properties(NSBitmapImageFileType::PNG, &NSDictionary::new()) }.ok_or("无法保存剪贴板图片")?;
    if png.length() > MAX_ITEM_BYTES { return Err("图片超过 20 MB，未加入历史".into()) }
    let ratio = (240.0 / width.max(height) as f64).min(1.0);
    let (thumb_width, thumb_height) = (((width as f64 * ratio).round() as isize).max(1), ((height as f64 * ratio).round() as isize).max(1));
    let thumbnail = unsafe {
        NSBitmapImageRep::initWithBitmapDataPlanes_pixelsWide_pixelsHigh_bitsPerSample_samplesPerPixel_hasAlpha_isPlanar_colorSpaceName_bytesPerRow_bitsPerPixel(
            NSBitmapImageRep::alloc(), std::ptr::null_mut(), thumb_width, thumb_height, 8, 4, true, false, NSDeviceRGBColorSpace, thumb_width * 4, 32,
        )
    }.ok_or("无法生成剪贴板图片预览")?;
    let image = NSImage::initWithSize(NSImage::alloc(), NSSize::new(width as f64, height as f64));
    image.addRepresentation(&bitmap);
    let context = NSGraphicsContext::graphicsContextWithBitmapImageRep(&thumbnail).ok_or("无法生成图片预览上下文")?;
    NSGraphicsContext::saveGraphicsState_class();
    NSGraphicsContext::setCurrentContext(Some(&context));
    image.drawInRect_fromRect_operation_fraction(
        NSRect::new(NSPoint::new(0.0, 0.0), NSSize::new(thumb_width as f64, thumb_height as f64)),
        NSRect::new(NSPoint::new(0.0, 0.0), NSSize::new(0.0, 0.0)), NSCompositingOperation::Copy, 1.0,
    );
    NSGraphicsContext::restoreGraphicsState_class();
    let thumbnail = unsafe { thumbnail.representationUsingType_properties(NSBitmapImageFileType::PNG, &NSDictionary::new()) }.ok_or("无法编码图片预览")?;
    Ok(Capture { kind: Kind::Image, data: png.to_vec(), preview: format!("{width} × {height}"), thumbnail: thumbnail.to_vec(), width: width as u32, height: height as u32 })
}

pub fn write_history(kind: &str, data: &[u8]) -> Result<isize, CallError> {
    autoreleasepool(|_| {
        let pasteboard = NSPasteboard::generalPasteboard();
        write(&pasteboard, kind, data)?;
        Ok(pasteboard.changeCount())
    })
}

fn write(pasteboard: &NSPasteboard, kind: &str, data: &[u8]) -> Result<(), CallError> {
    let success = match kind {
        "text" => {
            let text = std::str::from_utf8(data).map_err(|_| "文本记录损坏")?;
            pasteboard.clearContents();
            pasteboard.setString_forType(&NSString::from_str(text), unsafe { NSPasteboardTypeString })
        }
        "image" => {
            let data = NSData::from_vec(data.to_vec());
            pasteboard.clearContents();
            pasteboard.setData_forType(Some(&data), unsafe { NSPasteboardTypePNG })
        }
        "file" => {
            let paths: Vec<String> = serde_json::from_slice(data).map_err(|_| "文件记录损坏")?;
            if paths.is_empty() { return Err("文件记录为空".into()) }
            let mut items = vec![];
            for path in paths {
                if !std::path::Path::new(&path).exists() { return Err(CallError::new("not_found", format!("文件已移动或删除：{path}"))) }
                let url = tauri::Url::from_file_path(&path).map_err(|_| "文件路径不正确")?;
                let item = NSPasteboardItem::new();
                if !item.setString_forType(&NSString::from_str(url.as_str()), unsafe { NSPasteboardTypeFileURL }) { return Err("无法准备文件剪贴板".into()) }
                items.push(item);
            }
            let items: Vec<&ProtocolObject<dyn NSPasteboardWriting>> = items.iter().map(|item| ProtocolObject::from_ref(&**item)).collect();
            pasteboard.clearContents();
            pasteboard.writeObjects(&NSArray::from_slice(&items))
        }
        _ => return Err("不支持此剪贴板记录类型".into()),
    };
    if success { Ok(()) } else { Err("写入系统剪贴板失败，请重试".into()) }
}

#[cfg(test)]
mod tests {
    use super::*;
    // AppKit 剪贴板内部有共享缓存，原生测试与正式采集一样串行访问。
    static PASTEBOARD_TEST_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());
    #[test]
    fn 独立剪贴板文本图片文件往返且缺失文件不清空现有内容() {
        let _guard = PASTEBOARD_TEST_LOCK.lock().unwrap();
        autoreleasepool(|_| {
            let board = NSPasteboard::pasteboardWithUniqueName();
            write(&board, "text", "测试\n保留空白 ".as_bytes()).unwrap();
            assert_eq!(read(&board).unwrap().unwrap().data, "测试\n保留空白 ".as_bytes());
            let folder = std::env::temp_dir().join(format!("qingbox-clipboard-test-{}-{}", std::process::id(), super::super::now()));
            std::fs::create_dir(&folder).unwrap();
            let file = folder.join("中文 #1.txt");
            std::fs::write(&file, "测试文件").unwrap();
            let files = Capture::files(vec![file.to_string_lossy().into_owned(), folder.to_string_lossy().into_owned()]).unwrap();
            write(&board, "file", &files.data).unwrap();
            let captured = read(&board).unwrap().unwrap();
            assert_eq!(captured.kind, Kind::File);
            assert_eq!(captured.data, files.data);
            let png = include_bytes!("../../icons/128x128.png");
            write(&board, "image", png).unwrap();
            let captured = read(&board).unwrap().unwrap();
            assert_eq!(captured.kind, Kind::Image);
            assert_eq!((captured.width, captured.height), (128, 128));
            assert!(!captured.thumbnail.is_empty());
            let bitmap = NSBitmapImageRep::initWithData(NSBitmapImageRep::alloc(), &NSData::from_vec(png.to_vec())).unwrap();
            let tiff = unsafe { bitmap.representationUsingType_properties(NSBitmapImageFileType::TIFF, &NSDictionary::new()) }.unwrap();
            board.clearContents();
            board.setData_forType(Some(&tiff), unsafe { NSPasteboardTypeTIFF });
            let captured = read(&board).unwrap().unwrap();
            assert_eq!((captured.width, captured.height), (128, 128));
            assert!(captured.data.starts_with(b"\x89PNG"), "TIFF 截图应转成可恢复的 PNG");
            std::fs::remove_file(&file).unwrap();
            let missing = write(&board, "file", &files.data).unwrap_err();
            assert_eq!(missing.code, "not_found");
            assert!(missing.message.contains("移动或删除"));
            assert_eq!(read(&board).unwrap().unwrap().kind, Kind::Image);
            std::fs::remove_dir(&folder).unwrap();
            board.clearContents();
        });
    }
    #[test]
    fn 标记为敏感的剪贴板不进入历史() {
        let _guard = PASTEBOARD_TEST_LOCK.lock().unwrap();
        autoreleasepool(|_| {
            let board = NSPasteboard::pasteboardWithUniqueName();
            write(&board, "text", b"test-secret").unwrap();
            board.setString_forType(&NSString::from_str("1"), &NSString::from_str("org.nspasteboard.ConcealedType"));
            assert!(read(&board).unwrap().is_none());
            board.clearContents();
        });
    }
}
